from fastapi import APIRouter
from app.api.v1.endpoints import connections, datasets, dashboards, charts, queries, ai, auth, transforms, semantic_models, kpi, quickcharts, filters, drill, conditional_format, time_intelligence, rls, schedule, kodee, insights, cloud_connectors, workspaces, audit, embed, advanced_charts, subscriptions, reports, mobile, collaboration, sharing, shortcuts, search, sdk, plugins, theming, integrations, caching, query_optimization, background_jobs, performance_monitoring, workspace_management, user_management, billing, admin_dashboard, two_factor_auth, security_controls, compliance, security_audit, export, report_templates, scheduled_reports, report_subscriptions

api_router = APIRouter()

api_router.include_router(auth.router)
api_router.include_router(connections.router, prefix="/connections", tags=["connections"])
api_router.include_router(datasets.router, prefix="/datasets", tags=["datasets"])
api_router.include_router(dashboards.router, prefix="/dashboards", tags=["dashboards"])
api_router.include_router(charts.router, prefix="/charts", tags=["charts"])
api_router.include_router(queries.router, prefix="/queries", tags=["queries"])
api_router.include_router(ai.router, prefix="/ai", tags=["ai"])
api_router.include_router(transforms.router, prefix="/transforms", tags=["transforms"])
api_router.include_router(semantic_models.router, prefix="/models", tags=["models"])
api_router.include_router(kpi.router, prefix="/kpi", tags=["kpi"])
api_router.include_router(quickcharts.router, prefix="/quickcharts", tags=["quickcharts"])
api_router.include_router(filters.router, prefix="/filters", tags=["filters"])
api_router.include_router(drill.router, prefix="/drill", tags=["drill"])
api_router.include_router(conditional_format.router, prefix="/conditional-format", tags=["conditional-format"])
api_router.include_router(time_intelligence.router, prefix="/time-intelligence", tags=["time-intelligence"])
api_router.include_router(rls.router, prefix="/rls", tags=["row-level-security"])
api_router.include_router(schedule.router, prefix="/schedule", tags=["schedule-alerts"])
api_router.include_router(kodee.router, prefix="/kodee", tags=["kodee-nl-sql"])
api_router.include_router(insights.router, prefix="/insights", tags=["insights"])
api_router.include_router(cloud_connectors.router, prefix="/cloud", tags=["cloud-connectors"])
api_router.include_router(workspaces.router, prefix="/workspaces", tags=["workspaces"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(embed.router, prefix="/embed", tags=["embed"])
api_router.include_router(advanced_charts.router, prefix="/advanced-charts", tags=["advanced-charts"])
api_router.include_router(subscriptions.router, prefix="/subscriptions", tags=["subscriptions-alerts"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(mobile.router, prefix="/mobile", tags=["mobile"])
api_router.include_router(collaboration.router, prefix="/collaboration", tags=["collaboration"])
api_router.include_router(sharing.router, prefix="/sharing", tags=["sharing"])
api_router.include_router(shortcuts.router, prefix="/shortcuts", tags=["shortcuts-commands"])
api_router.include_router(search.router, prefix="/search", tags=["search-navigation"])
api_router.include_router(sdk.router, prefix="/sdk", tags=["sdk-api"])
api_router.include_router(plugins.router, prefix="/plugins", tags=["plugins"])
api_router.include_router(theming.router, prefix="/theming", tags=["theming"])
api_router.include_router(integrations.router, prefix="/integrations", tags=["integrations"])
api_router.include_router(caching.router, prefix="/cache", tags=["caching"])
api_router.include_router(query_optimization.router, prefix="/query-optimization", tags=["query-optimization"])
api_router.include_router(background_jobs.router, prefix="/jobs", tags=["background-jobs"])
api_router.include_router(performance_monitoring.router, prefix="/monitoring", tags=["performance-monitoring"])
api_router.include_router(workspace_management.router, prefix="/workspace-mgmt", tags=["workspace-management"])
api_router.include_router(user_management.router, prefix="/user-mgmt", tags=["user-management"])
api_router.include_router(billing.router, prefix="/billing", tags=["billing"])
api_router.include_router(admin_dashboard.router, prefix="/admin", tags=["admin-dashboard"])
api_router.include_router(two_factor_auth.router, prefix="/2fa", tags=["two-factor-auth"])
api_router.include_router(security_controls.router, prefix="/security", tags=["security-controls"])
api_router.include_router(compliance.router, prefix="/compliance", tags=["compliance"])
api_router.include_router(security_audit.router, prefix="/security-audit", tags=["security-audit"])
api_router.include_router(export.router, prefix="/export", tags=["export"])
api_router.include_router(report_templates.router, prefix="/report-templates", tags=["report-templates"])
api_router.include_router(scheduled_reports.router, prefix="/scheduled-reports", tags=["scheduled-reports"])
api_router.include_router(report_subscriptions.router, prefix="/subscriptions", tags=["report-subscriptions"])
